# Generated by Django 3.2.3 on 2021-05-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210523_0856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='kakao_id',
            new_name='social_id',
        ),
        migrations.AddField(
            model_name='user',
            name='social_platform',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
