# Generated by Django 3.2.3 on 2021-05-23 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210523_0900'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.AddField(
            model_name='user',
            name='thumbnail_image',
            field=models.URLField(blank=True),
        ),
    ]
